name: Android

on: [ pull_request ]

jobs:
  test:
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: run tests
        uses: reactivecircus/android-emulator-runner@v1
        with:
          api-level: 29
          script: ./gradlew rootCoverageReport
      - name: upload code coverage report
        uses: codecov/codecov-action@v2.1.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./build/reports/jacoco.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true